language: node_js
node_js:
 - "node"

cache: npm

before_install: cd presentation-client

script: npm run build

deploy:
 provider: pages
 skip_cleanup: true
 github_token: $GITHUB_TOKEN
 local_dir: dist
 on:
   branch: master