apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: presentation-server
spec:
  rules:
  - host: dev-api.v2tools.com
    http:
      paths:
      - path: /presentations/api/(.*)
        backend:
          serviceName: presentation-server
          servicePort: grpc-web
  # tls:
  # - hosts:
  #   - dev-api.v2tools.com
