// Code generated by protoc-gen-go. DO NOT EDIT.
// source: presentation.proto

package presentation

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PresentationUpdate struct {
	SlideName            string   `protobuf:"bytes,1,opt,name=SlideName,proto3" json:"SlideName,omitempty"`
	SubSlide             string   `protobuf:"bytes,2,opt,name=SubSlide,proto3" json:"SubSlide,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PresentationUpdate) Reset()         { *m = PresentationUpdate{} }
func (m *PresentationUpdate) String() string { return proto.CompactTextString(m) }
func (*PresentationUpdate) ProtoMessage()    {}
func (*PresentationUpdate) Descriptor() ([]byte, []int) {
	return fileDescriptor_f16293ba8a203772, []int{0}
}

func (m *PresentationUpdate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PresentationUpdate.Unmarshal(m, b)
}
func (m *PresentationUpdate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PresentationUpdate.Marshal(b, m, deterministic)
}
func (m *PresentationUpdate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PresentationUpdate.Merge(m, src)
}
func (m *PresentationUpdate) XXX_Size() int {
	return xxx_messageInfo_PresentationUpdate.Size(m)
}
func (m *PresentationUpdate) XXX_DiscardUnknown() {
	xxx_messageInfo_PresentationUpdate.DiscardUnknown(m)
}

var xxx_messageInfo_PresentationUpdate proto.InternalMessageInfo

func (m *PresentationUpdate) GetSlideName() string {
	if m != nil {
		return m.SlideName
	}
	return ""
}

func (m *PresentationUpdate) GetSubSlide() string {
	if m != nil {
		return m.SubSlide
	}
	return ""
}

type ChatMessage struct {
	User                 string   `protobuf:"bytes,1,opt,name=User,proto3" json:"User,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=Message,proto3" json:"Message,omitempty"`
	Timestamp            int64    `protobuf:"varint,3,opt,name=Timestamp,proto3" json:"Timestamp,omitempty"`
	MessageId            string   `protobuf:"bytes,4,opt,name=MessageId,proto3" json:"MessageId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChatMessage) Reset()         { *m = ChatMessage{} }
func (m *ChatMessage) String() string { return proto.CompactTextString(m) }
func (*ChatMessage) ProtoMessage()    {}
func (*ChatMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_f16293ba8a203772, []int{1}
}

func (m *ChatMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChatMessage.Unmarshal(m, b)
}
func (m *ChatMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChatMessage.Marshal(b, m, deterministic)
}
func (m *ChatMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChatMessage.Merge(m, src)
}
func (m *ChatMessage) XXX_Size() int {
	return xxx_messageInfo_ChatMessage.Size(m)
}
func (m *ChatMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_ChatMessage.DiscardUnknown(m)
}

var xxx_messageInfo_ChatMessage proto.InternalMessageInfo

func (m *ChatMessage) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

func (m *ChatMessage) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *ChatMessage) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *ChatMessage) GetMessageId() string {
	if m != nil {
		return m.MessageId
	}
	return ""
}

type ChatMessageResponse struct {
	Error                bool         `protobuf:"varint,1,opt,name=Error,proto3" json:"Error,omitempty"`
	ErrorMessage         string       `protobuf:"bytes,2,opt,name=ErrorMessage,proto3" json:"ErrorMessage,omitempty"`
	Message              *ChatMessage `protobuf:"bytes,3,opt,name=Message,proto3" json:"Message,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ChatMessageResponse) Reset()         { *m = ChatMessageResponse{} }
func (m *ChatMessageResponse) String() string { return proto.CompactTextString(m) }
func (*ChatMessageResponse) ProtoMessage()    {}
func (*ChatMessageResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f16293ba8a203772, []int{2}
}

func (m *ChatMessageResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChatMessageResponse.Unmarshal(m, b)
}
func (m *ChatMessageResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChatMessageResponse.Marshal(b, m, deterministic)
}
func (m *ChatMessageResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChatMessageResponse.Merge(m, src)
}
func (m *ChatMessageResponse) XXX_Size() int {
	return xxx_messageInfo_ChatMessageResponse.Size(m)
}
func (m *ChatMessageResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ChatMessageResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ChatMessageResponse proto.InternalMessageInfo

func (m *ChatMessageResponse) GetError() bool {
	if m != nil {
		return m.Error
	}
	return false
}

func (m *ChatMessageResponse) GetErrorMessage() string {
	if m != nil {
		return m.ErrorMessage
	}
	return ""
}

func (m *ChatMessageResponse) GetMessage() *ChatMessage {
	if m != nil {
		return m.Message
	}
	return nil
}

type ActivePresentationResponse struct {
	Error                bool     `protobuf:"varint,1,opt,name=Error,proto3" json:"Error,omitempty"`
	IsActive             bool     `protobuf:"varint,2,opt,name=IsActive,proto3" json:"IsActive,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ActivePresentationResponse) Reset()         { *m = ActivePresentationResponse{} }
func (m *ActivePresentationResponse) String() string { return proto.CompactTextString(m) }
func (*ActivePresentationResponse) ProtoMessage()    {}
func (*ActivePresentationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f16293ba8a203772, []int{3}
}

func (m *ActivePresentationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ActivePresentationResponse.Unmarshal(m, b)
}
func (m *ActivePresentationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ActivePresentationResponse.Marshal(b, m, deterministic)
}
func (m *ActivePresentationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ActivePresentationResponse.Merge(m, src)
}
func (m *ActivePresentationResponse) XXX_Size() int {
	return xxx_messageInfo_ActivePresentationResponse.Size(m)
}
func (m *ActivePresentationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ActivePresentationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ActivePresentationResponse proto.InternalMessageInfo

func (m *ActivePresentationResponse) GetError() bool {
	if m != nil {
		return m.Error
	}
	return false
}

func (m *ActivePresentationResponse) GetIsActive() bool {
	if m != nil {
		return m.IsActive
	}
	return false
}

type StartPresentationRequest struct {
	Password             string   `protobuf:"bytes,1,opt,name=Password,proto3" json:"Password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StartPresentationRequest) Reset()         { *m = StartPresentationRequest{} }
func (m *StartPresentationRequest) String() string { return proto.CompactTextString(m) }
func (*StartPresentationRequest) ProtoMessage()    {}
func (*StartPresentationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f16293ba8a203772, []int{4}
}

func (m *StartPresentationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StartPresentationRequest.Unmarshal(m, b)
}
func (m *StartPresentationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StartPresentationRequest.Marshal(b, m, deterministic)
}
func (m *StartPresentationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StartPresentationRequest.Merge(m, src)
}
func (m *StartPresentationRequest) XXX_Size() int {
	return xxx_messageInfo_StartPresentationRequest.Size(m)
}
func (m *StartPresentationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StartPresentationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StartPresentationRequest proto.InternalMessageInfo

func (m *StartPresentationRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type StartPresentationResponse struct {
	Error                bool     `protobuf:"varint,1,opt,name=Error,proto3" json:"Error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StartPresentationResponse) Reset()         { *m = StartPresentationResponse{} }
func (m *StartPresentationResponse) String() string { return proto.CompactTextString(m) }
func (*StartPresentationResponse) ProtoMessage()    {}
func (*StartPresentationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f16293ba8a203772, []int{5}
}

func (m *StartPresentationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StartPresentationResponse.Unmarshal(m, b)
}
func (m *StartPresentationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StartPresentationResponse.Marshal(b, m, deterministic)
}
func (m *StartPresentationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StartPresentationResponse.Merge(m, src)
}
func (m *StartPresentationResponse) XXX_Size() int {
	return xxx_messageInfo_StartPresentationResponse.Size(m)
}
func (m *StartPresentationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StartPresentationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StartPresentationResponse proto.InternalMessageInfo

func (m *StartPresentationResponse) GetError() bool {
	if m != nil {
		return m.Error
	}
	return false
}

type PostChatMessageResponse struct {
	Error                bool     `protobuf:"varint,1,opt,name=Error,proto3" json:"Error,omitempty"`
	ErrorMessage         string   `protobuf:"bytes,2,opt,name=ErrorMessage,proto3" json:"ErrorMessage,omitempty"`
	MessageId            string   `protobuf:"bytes,3,opt,name=MessageId,proto3" json:"MessageId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PostChatMessageResponse) Reset()         { *m = PostChatMessageResponse{} }
func (m *PostChatMessageResponse) String() string { return proto.CompactTextString(m) }
func (*PostChatMessageResponse) ProtoMessage()    {}
func (*PostChatMessageResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f16293ba8a203772, []int{6}
}

func (m *PostChatMessageResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PostChatMessageResponse.Unmarshal(m, b)
}
func (m *PostChatMessageResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PostChatMessageResponse.Marshal(b, m, deterministic)
}
func (m *PostChatMessageResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PostChatMessageResponse.Merge(m, src)
}
func (m *PostChatMessageResponse) XXX_Size() int {
	return xxx_messageInfo_PostChatMessageResponse.Size(m)
}
func (m *PostChatMessageResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PostChatMessageResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PostChatMessageResponse proto.InternalMessageInfo

func (m *PostChatMessageResponse) GetError() bool {
	if m != nil {
		return m.Error
	}
	return false
}

func (m *PostChatMessageResponse) GetErrorMessage() string {
	if m != nil {
		return m.ErrorMessage
	}
	return ""
}

func (m *PostChatMessageResponse) GetMessageId() string {
	if m != nil {
		return m.MessageId
	}
	return ""
}

func init() {
	proto.RegisterType((*PresentationUpdate)(nil), "presentation.PresentationUpdate")
	proto.RegisterType((*ChatMessage)(nil), "presentation.ChatMessage")
	proto.RegisterType((*ChatMessageResponse)(nil), "presentation.ChatMessageResponse")
	proto.RegisterType((*ActivePresentationResponse)(nil), "presentation.ActivePresentationResponse")
	proto.RegisterType((*StartPresentationRequest)(nil), "presentation.StartPresentationRequest")
	proto.RegisterType((*StartPresentationResponse)(nil), "presentation.StartPresentationResponse")
	proto.RegisterType((*PostChatMessageResponse)(nil), "presentation.PostChatMessageResponse")
}

func init() { proto.RegisterFile("presentation.proto", fileDescriptor_f16293ba8a203772) }

var fileDescriptor_f16293ba8a203772 = []byte{
	// 417 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x93, 0xcf, 0xaf, 0xd2, 0x40,
	0x10, 0xc7, 0x53, 0xfb, 0xd4, 0xbe, 0x79, 0x24, 0x4f, 0x47, 0xa3, 0xa5, 0x7a, 0xc0, 0x4d, 0x54,
	0x4e, 0x05, 0x21, 0xf1, 0x6e, 0x0c, 0x31, 0x98, 0xd8, 0x90, 0x56, 0xbc, 0x2f, 0x76, 0xc4, 0x26,
	0xb4, 0x5b, 0xba, 0x8b, 0xc4, 0xbb, 0xff, 0x98, 0xff, 0x99, 0xe9, 0x0f, 0x4a, 0x17, 0x28, 0x78,
	0x78, 0xb7, 0x9d, 0xdf, 0x9f, 0x7c, 0x67, 0x16, 0x30, 0xcd, 0x48, 0x52, 0xa2, 0xb8, 0x8a, 0x44,
	0xe2, 0xa6, 0x99, 0x50, 0x02, 0x3b, 0x4d, 0x9f, 0xf3, 0x62, 0x29, 0xc4, 0x72, 0x45, 0x83, 0x22,
	0xb6, 0xd8, 0xfc, 0x18, 0x50, 0x9c, 0xaa, 0xdf, 0x65, 0x2a, 0xf3, 0x00, 0x67, 0x8d, 0xe4, 0x79,
	0x1a, 0x72, 0x45, 0xf8, 0x12, 0xae, 0x83, 0x55, 0x14, 0x92, 0xc7, 0x63, 0xb2, 0x8d, 0x9e, 0xd1,
	0xbf, 0xf6, 0xf7, 0x0e, 0x74, 0xc0, 0x0a, 0x36, 0x8b, 0xc2, 0xb6, 0xef, 0x15, 0xc1, 0xda, 0x66,
	0x5b, 0xb8, 0xf9, 0xf8, 0x93, 0xab, 0x2f, 0x24, 0x25, 0x5f, 0x12, 0x22, 0x5c, 0xcd, 0x25, 0x65,
	0x55, 0x8f, 0xe2, 0x8d, 0x36, 0x3c, 0xac, 0xc2, 0x55, 0xf5, 0xce, 0xcc, 0xc7, 0x7e, 0x8d, 0x62,
	0x92, 0x8a, 0xc7, 0xa9, 0x6d, 0xf6, 0x8c, 0xbe, 0xe9, 0xef, 0x1d, 0x79, 0xb4, 0x4a, 0x9c, 0x86,
	0xf6, 0x55, 0x09, 0x55, 0x3b, 0xd8, 0x1f, 0x03, 0x9e, 0x34, 0x26, 0xfb, 0x24, 0x53, 0x91, 0x48,
	0xc2, 0xa7, 0x70, 0x7f, 0x92, 0x65, 0xa2, 0x44, 0xb0, 0xfc, 0xd2, 0x40, 0x06, 0x9d, 0xe2, 0xa1,
	0x83, 0x68, 0x3e, 0x1c, 0xef, 0x39, 0x73, 0x96, 0x9b, 0x51, 0xd7, 0xd5, 0xb4, 0x6e, 0x4e, 0xdb,
	0x65, 0x32, 0x0f, 0x9c, 0x0f, 0xdf, 0x55, 0xf4, 0x8b, 0x9a, 0xaa, 0x5e, 0x80, 0x71, 0xc0, 0x9a,
	0xca, 0xb2, 0xaa, 0x00, 0xb1, 0xfc, 0xda, 0x66, 0xef, 0xc1, 0x0e, 0x14, 0xcf, 0x94, 0xde, 0x6e,
	0xbd, 0x21, 0xa9, 0xf2, 0xba, 0x19, 0x97, 0x72, 0x2b, 0xb2, 0xb0, 0x12, 0xb8, 0xb6, 0xd9, 0x3b,
	0xe8, 0x9e, 0xa8, 0x3b, 0x87, 0xc1, 0xd6, 0xf0, 0x7c, 0x26, 0xa4, 0xba, 0x5b, 0x11, 0xb5, 0xa5,
	0x99, 0x07, 0x4b, 0x1b, 0xfd, 0x35, 0xa1, 0xd3, 0x24, 0xc4, 0x6f, 0x80, 0xc7, 0xf2, 0xe1, 0x33,
	0xb7, 0x3c, 0x61, 0x77, 0x77, 0xc2, 0xee, 0x24, 0x3f, 0x61, 0xa7, 0xaf, 0x2f, 0xe4, 0x8c, 0xf0,
	0x21, 0x3c, 0x3e, 0x92, 0x03, 0xdf, 0xe8, 0xe5, 0x6d, 0x3a, 0x3b, 0x6f, 0x2f, 0xe6, 0x55, 0x53,
	0x3c, 0x78, 0xf4, 0x59, 0x44, 0xc9, 0x7f, 0xb1, 0xf7, 0xf4, 0xa6, 0xc7, 0x9f, 0x70, 0x68, 0xa0,
	0x07, 0xb7, 0x9f, 0xa8, 0xb9, 0x10, 0xd9, 0xda, 0xee, 0x55, 0xfb, 0x6d, 0x56, 0x74, 0x43, 0x03,
	0x03, 0xb8, 0x3d, 0xd8, 0x30, 0xb6, 0xdf, 0xb4, 0xf3, 0xfa, 0x80, 0xf0, 0xf4, 0x6d, 0x2c, 0x1e,
	0x14, 0x24, 0xe3, 0x7f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x64, 0x60, 0xe9, 0x1a, 0x89, 0x04, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PresentationClient is the client API for Presentation service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PresentationClient interface {
	ActivePresentation(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*ActivePresentationResponse, error)
	StartPresentation(ctx context.Context, in *StartPresentationRequest, opts ...grpc.CallOption) (*StartPresentationResponse, error)
	JoinPresentation(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (Presentation_JoinPresentationClient, error)
	GetChatMessages(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (Presentation_GetChatMessagesClient, error)
	PostChatMessage(ctx context.Context, in *ChatMessage, opts ...grpc.CallOption) (*PostChatMessageResponse, error)
}

type presentationClient struct {
	cc *grpc.ClientConn
}

func NewPresentationClient(cc *grpc.ClientConn) PresentationClient {
	return &presentationClient{cc}
}

func (c *presentationClient) ActivePresentation(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*ActivePresentationResponse, error) {
	out := new(ActivePresentationResponse)
	err := c.cc.Invoke(ctx, "/presentation.Presentation/ActivePresentation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *presentationClient) StartPresentation(ctx context.Context, in *StartPresentationRequest, opts ...grpc.CallOption) (*StartPresentationResponse, error) {
	out := new(StartPresentationResponse)
	err := c.cc.Invoke(ctx, "/presentation.Presentation/StartPresentation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *presentationClient) JoinPresentation(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (Presentation_JoinPresentationClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Presentation_serviceDesc.Streams[0], "/presentation.Presentation/JoinPresentation", opts...)
	if err != nil {
		return nil, err
	}
	x := &presentationJoinPresentationClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Presentation_JoinPresentationClient interface {
	Recv() (*PresentationUpdate, error)
	grpc.ClientStream
}

type presentationJoinPresentationClient struct {
	grpc.ClientStream
}

func (x *presentationJoinPresentationClient) Recv() (*PresentationUpdate, error) {
	m := new(PresentationUpdate)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *presentationClient) GetChatMessages(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (Presentation_GetChatMessagesClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Presentation_serviceDesc.Streams[1], "/presentation.Presentation/GetChatMessages", opts...)
	if err != nil {
		return nil, err
	}
	x := &presentationGetChatMessagesClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Presentation_GetChatMessagesClient interface {
	Recv() (*ChatMessageResponse, error)
	grpc.ClientStream
}

type presentationGetChatMessagesClient struct {
	grpc.ClientStream
}

func (x *presentationGetChatMessagesClient) Recv() (*ChatMessageResponse, error) {
	m := new(ChatMessageResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *presentationClient) PostChatMessage(ctx context.Context, in *ChatMessage, opts ...grpc.CallOption) (*PostChatMessageResponse, error) {
	out := new(PostChatMessageResponse)
	err := c.cc.Invoke(ctx, "/presentation.Presentation/PostChatMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PresentationServer is the server API for Presentation service.
type PresentationServer interface {
	ActivePresentation(context.Context, *empty.Empty) (*ActivePresentationResponse, error)
	StartPresentation(context.Context, *StartPresentationRequest) (*StartPresentationResponse, error)
	JoinPresentation(*empty.Empty, Presentation_JoinPresentationServer) error
	GetChatMessages(*empty.Empty, Presentation_GetChatMessagesServer) error
	PostChatMessage(context.Context, *ChatMessage) (*PostChatMessageResponse, error)
}

// UnimplementedPresentationServer can be embedded to have forward compatible implementations.
type UnimplementedPresentationServer struct {
}

func (*UnimplementedPresentationServer) ActivePresentation(ctx context.Context, req *empty.Empty) (*ActivePresentationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ActivePresentation not implemented")
}
func (*UnimplementedPresentationServer) StartPresentation(ctx context.Context, req *StartPresentationRequest) (*StartPresentationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartPresentation not implemented")
}
func (*UnimplementedPresentationServer) JoinPresentation(req *empty.Empty, srv Presentation_JoinPresentationServer) error {
	return status.Errorf(codes.Unimplemented, "method JoinPresentation not implemented")
}
func (*UnimplementedPresentationServer) GetChatMessages(req *empty.Empty, srv Presentation_GetChatMessagesServer) error {
	return status.Errorf(codes.Unimplemented, "method GetChatMessages not implemented")
}
func (*UnimplementedPresentationServer) PostChatMessage(ctx context.Context, req *ChatMessage) (*PostChatMessageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PostChatMessage not implemented")
}

func RegisterPresentationServer(s *grpc.Server, srv PresentationServer) {
	s.RegisterService(&_Presentation_serviceDesc, srv)
}

func _Presentation_ActivePresentation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PresentationServer).ActivePresentation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/presentation.Presentation/ActivePresentation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PresentationServer).ActivePresentation(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Presentation_StartPresentation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartPresentationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PresentationServer).StartPresentation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/presentation.Presentation/StartPresentation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PresentationServer).StartPresentation(ctx, req.(*StartPresentationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Presentation_JoinPresentation_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(empty.Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PresentationServer).JoinPresentation(m, &presentationJoinPresentationServer{stream})
}

type Presentation_JoinPresentationServer interface {
	Send(*PresentationUpdate) error
	grpc.ServerStream
}

type presentationJoinPresentationServer struct {
	grpc.ServerStream
}

func (x *presentationJoinPresentationServer) Send(m *PresentationUpdate) error {
	return x.ServerStream.SendMsg(m)
}

func _Presentation_GetChatMessages_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(empty.Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PresentationServer).GetChatMessages(m, &presentationGetChatMessagesServer{stream})
}

type Presentation_GetChatMessagesServer interface {
	Send(*ChatMessageResponse) error
	grpc.ServerStream
}

type presentationGetChatMessagesServer struct {
	grpc.ServerStream
}

func (x *presentationGetChatMessagesServer) Send(m *ChatMessageResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _Presentation_PostChatMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChatMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PresentationServer).PostChatMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/presentation.Presentation/PostChatMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PresentationServer).PostChatMessage(ctx, req.(*ChatMessage))
	}
	return interceptor(ctx, in, info, handler)
}

var _Presentation_serviceDesc = grpc.ServiceDesc{
	ServiceName: "presentation.Presentation",
	HandlerType: (*PresentationServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ActivePresentation",
			Handler:    _Presentation_ActivePresentation_Handler,
		},
		{
			MethodName: "StartPresentation",
			Handler:    _Presentation_StartPresentation_Handler,
		},
		{
			MethodName: "PostChatMessage",
			Handler:    _Presentation_PostChatMessage_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "JoinPresentation",
			Handler:       _Presentation_JoinPresentation_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetChatMessages",
			Handler:       _Presentation_GetChatMessages_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "presentation.proto",
}
