apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: presentation-server
spec:
  rules:
  - host: api.v2tools.com
    http:
      paths:
      - path: /presentations/
        backend:
          serviceName: presentation-server
          servicePort: grpc-web
  # tls:
  # - hosts:
  #   - api.v2tools.com
