// Code generated by protoc-gen-go. DO NOT EDIT.
// source: models.proto

package voting

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PollType int32

const (
	PollType_Single   PollType = 0
	PollType_Binary   PollType = 1
	PollType_Multiple PollType = 2
)

var PollType_name = map[int32]string{
	0: "Single",
	1: "Binary",
	2: "Multiple",
}

var PollType_value = map[string]int32{
	"Single":   0,
	"Binary":   1,
	"Multiple": 2,
}

func (x PollType) String() string {
	return proto.EnumName(PollType_name, int32(x))
}

func (PollType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_0b5431a010549573, []int{0}
}

type Vote struct {
	UserId               string   `protobuf:"bytes,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	UserCode             string   `protobuf:"bytes,2,opt,name=UserCode,proto3" json:"UserCode,omitempty"`
	PollId               string   `protobuf:"bytes,3,opt,name=PollId,proto3" json:"PollId,omitempty"`
	OptionId             string   `protobuf:"bytes,4,opt,name=OptionId,proto3" json:"OptionId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Vote) Reset()         { *m = Vote{} }
func (m *Vote) String() string { return proto.CompactTextString(m) }
func (*Vote) ProtoMessage()    {}
func (*Vote) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b5431a010549573, []int{0}
}

func (m *Vote) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Vote.Unmarshal(m, b)
}
func (m *Vote) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Vote.Marshal(b, m, deterministic)
}
func (m *Vote) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Vote.Merge(m, src)
}
func (m *Vote) XXX_Size() int {
	return xxx_messageInfo_Vote.Size(m)
}
func (m *Vote) XXX_DiscardUnknown() {
	xxx_messageInfo_Vote.DiscardUnknown(m)
}

var xxx_messageInfo_Vote proto.InternalMessageInfo

func (m *Vote) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *Vote) GetUserCode() string {
	if m != nil {
		return m.UserCode
	}
	return ""
}

func (m *Vote) GetPollId() string {
	if m != nil {
		return m.PollId
	}
	return ""
}

func (m *Vote) GetOptionId() string {
	if m != nil {
		return m.OptionId
	}
	return ""
}

type Poll struct {
	Id                   string    `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Order                int32     `protobuf:"varint,2,opt,name=Order,proto3" json:"Order,omitempty"`
	Summary              string    `protobuf:"bytes,3,opt,name=Summary,proto3" json:"Summary,omitempty"`
	Options              []*Option `protobuf:"bytes,4,rep,name=Options,proto3" json:"Options,omitempty"`
	Type                 PollType  `protobuf:"varint,5,opt,name=Type,proto3,enum=voting.models.PollType" json:"Type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Poll) Reset()         { *m = Poll{} }
func (m *Poll) String() string { return proto.CompactTextString(m) }
func (*Poll) ProtoMessage()    {}
func (*Poll) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b5431a010549573, []int{1}
}

func (m *Poll) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Poll.Unmarshal(m, b)
}
func (m *Poll) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Poll.Marshal(b, m, deterministic)
}
func (m *Poll) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Poll.Merge(m, src)
}
func (m *Poll) XXX_Size() int {
	return xxx_messageInfo_Poll.Size(m)
}
func (m *Poll) XXX_DiscardUnknown() {
	xxx_messageInfo_Poll.DiscardUnknown(m)
}

var xxx_messageInfo_Poll proto.InternalMessageInfo

func (m *Poll) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Poll) GetOrder() int32 {
	if m != nil {
		return m.Order
	}
	return 0
}

func (m *Poll) GetSummary() string {
	if m != nil {
		return m.Summary
	}
	return ""
}

func (m *Poll) GetOptions() []*Option {
	if m != nil {
		return m.Options
	}
	return nil
}

func (m *Poll) GetType() PollType {
	if m != nil {
		return m.Type
	}
	return PollType_Single
}

type Option struct {
	Id                   string   `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Option) Reset()         { *m = Option{} }
func (m *Option) String() string { return proto.CompactTextString(m) }
func (*Option) ProtoMessage()    {}
func (*Option) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b5431a010549573, []int{2}
}

func (m *Option) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Option.Unmarshal(m, b)
}
func (m *Option) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Option.Marshal(b, m, deterministic)
}
func (m *Option) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Option.Merge(m, src)
}
func (m *Option) XXX_Size() int {
	return xxx_messageInfo_Option.Size(m)
}
func (m *Option) XXX_DiscardUnknown() {
	xxx_messageInfo_Option.DiscardUnknown(m)
}

var xxx_messageInfo_Option proto.InternalMessageInfo

func (m *Option) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Option) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterEnum("voting.models.PollType", PollType_name, PollType_value)
	proto.RegisterType((*Vote)(nil), "voting.models.Vote")
	proto.RegisterType((*Poll)(nil), "voting.models.Poll")
	proto.RegisterType((*Option)(nil), "voting.models.Option")
}

func init() { proto.RegisterFile("models.proto", fileDescriptor_0b5431a010549573) }

var fileDescriptor_0b5431a010549573 = []byte{
	// 278 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x91, 0x5f, 0x4f, 0x83, 0x30,
	0x14, 0xc5, 0x85, 0x75, 0x0c, 0xaf, 0x73, 0x21, 0x37, 0xfe, 0x69, 0x7c, 0x22, 0x3c, 0x11, 0x35,
	0x68, 0xe6, 0x37, 0x98, 0x4f, 0x3c, 0xe8, 0x0c, 0x53, 0x1f, 0x7c, 0xc3, 0xb4, 0x59, 0x48, 0x0a,
	0x25, 0xa5, 0x33, 0xe1, 0xfb, 0xf8, 0x41, 0x4d, 0xdb, 0x75, 0x89, 0xfa, 0x76, 0x0f, 0xe7, 0xfc,
	0x38, 0xb7, 0x2d, 0xcc, 0x5b, 0xc9, 0xb8, 0x18, 0x8a, 0x5e, 0x49, 0x2d, 0xf1, 0xf4, 0x4b, 0xea,
	0xa6, 0xdb, 0x16, 0xee, 0x63, 0xd6, 0x01, 0x79, 0x97, 0x9a, 0xe3, 0x05, 0x44, 0x6f, 0x03, 0x57,
	0x25, 0xa3, 0x41, 0x1a, 0xe4, 0xc7, 0xd5, 0x5e, 0xe1, 0x15, 0xc4, 0x66, 0x7a, 0x94, 0x8c, 0xd3,
	0xd0, 0x3a, 0x07, 0x6d, 0x98, 0x17, 0x29, 0x44, 0xc9, 0xe8, 0xc4, 0x31, 0x4e, 0x19, 0x66, 0xdd,
	0xeb, 0x46, 0x76, 0x25, 0xa3, 0xc4, 0x31, 0x5e, 0x67, 0xdf, 0x01, 0x10, 0x13, 0xc3, 0x05, 0x84,
	0x87, 0xb2, 0xb0, 0x64, 0x78, 0x06, 0xd3, 0xb5, 0x62, 0x5c, 0xd9, 0x96, 0x69, 0xe5, 0x04, 0x52,
	0x98, 0x6d, 0x76, 0x6d, 0x5b, 0xab, 0x71, 0xdf, 0xe1, 0x25, 0xde, 0xc1, 0xcc, 0xfd, 0x74, 0xa0,
	0x24, 0x9d, 0xe4, 0x27, 0xcb, 0xf3, 0xe2, 0xd7, 0xc9, 0x0a, 0xe7, 0x56, 0x3e, 0x85, 0x37, 0x40,
	0x5e, 0xc7, 0x9e, 0xd3, 0x69, 0x1a, 0xe4, 0x8b, 0xe5, 0xe5, 0x9f, 0xb4, 0xd9, 0xc9, 0xd8, 0x95,
	0x0d, 0x65, 0xb7, 0x10, 0x39, 0xee, 0xdf, 0x9e, 0x08, 0xe4, 0xb9, 0x6e, 0xfd, 0x65, 0xd8, 0xf9,
	0xfa, 0x1e, 0x62, 0xcf, 0x23, 0x40, 0xb4, 0x69, 0xba, 0xad, 0xe0, 0xc9, 0x91, 0x99, 0x57, 0x4d,
	0x57, 0xab, 0x31, 0x09, 0x70, 0x0e, 0xf1, 0xd3, 0x4e, 0xe8, 0xa6, 0x17, 0x3c, 0x09, 0x57, 0xf1,
	0x47, 0xe4, 0xfa, 0x3f, 0x23, 0xfb, 0x2c, 0x0f, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xca, 0x73,
	0x5d, 0x08, 0xa6, 0x01, 0x00, 0x00,
}
